# Generated by Django 5.2.4 on 2025-07-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_collection_collectionwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл вашей работы (необязательно)', null=True, upload_to='works/pdfs/', verbose_name='PDF файл'),
        ),
    ]
