# Generated by Django 5.2.4 on 2025-07-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_work_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение обложки для вашей работы (необязательно)', null=True, upload_to='works/covers/', verbose_name='Обложка работы'),
        ),
    ]
