# Generated by Django 5.2.4 on 2025-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_work_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
