# Generated by Django 5.2.4 on 2025-07-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_work_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
