# Generated by Django 5.2.4 on 2025-07-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('manager', 'Менеджер'), ('administrator', 'Администратор')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
