# Generated by Django 5.2.4 on 2025-07-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_collection_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение обложки для коллекции (необязательно)', null=True, upload_to='collections/covers/', verbose_name='Обложка коллекции'),
        ),
    ]
