# Generated by Django 5.2.4 on 2025-07-08 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_collection_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='processing_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Обрабатывает менеджер'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='processing_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание обработки'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки'),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('resolved', 'Завершена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
